---
- name: install pip package
  apt:
    name: "{{ pip_package }}"
    state: present

- name: ensure latest pip
  pip:
    name: pip
    executable: "{{ pip_executable | default(omit) }}"
    version: "{{ pip_version }}"

- name: install various pip packages
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    virtualenv: "{{ item.virtualenv | default(omit) }}"
    virtualenv_python: "{{ item.virtualenv_python | default(omit) }}"
  with_items: "{{ pip_install_packages }}"
